force-app/main/default/objects/Quick_Text__mdt/Quick_Text__mdt.object-meta.xml
<CustomObject>
    <label>Quick Text</label>
    <pluralLabel>Quick Text</pluralLabel>
</CustomObject>

force-app/main/default/objects/Quick_Text__mdt/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quick_Text__mdt/fields/Object_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_Name__c</fullName>
    <label>Object Name</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
                <default>true</default>
                <label>Case</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuickTextClass.cls
public class QuickTextClass {
    
    @AuraEnabled
    public static List<String> getAllQiuckText(String itemId, String objectAPIName) {
        //String sMsg = 'Hi, {! FirstName }. This is test. Your Last Name is {!LastName}';
        //sMsg = sMsg.replaceAll('\\{! ', '\\{!').replaceAll(' }', '}');
        //String sObjectName = 'Contact';
        String sQuery = 'select Id';
        //String itemId = '0035400000CxuZq';
        //String[] sMsgArr = sMsg.split('\\{!');
        Set<String> listFields = new Set<String>();
        List<String> listMsg = new List<String>();
        Integer indexOfMsg = 0;
        for(Quick_Text__mdt qt : [select Message__c from Quick_Text__mdt where Object_Name__c =: objectAPIName]) {
            listMsg.add(qt.Message__c);
        }
        for(String sMsg : listMsg) {
            System.debug('sMsg   '+sMsg);
            if(sMsg.indexOf('{!') != -1) {
                indexOfMsg = listMsg.indexOf(sMsg);
                sMsg = sMsg.replaceAll('\\{! ', '\\{!').replaceAll(' }', '}');
                listMsg.set(indexOfMsg, sMsg);
                for(String msg : sMsg.split('\\{!')) {                    
                    if(msg.indexOf('}') != -1)
                        listFields.add(msg.substring(0, msg.indexOf('}')));
                }
            }
        }
        if(!listFields.isEmpty()) {	
            for(String field : listFields) {
                sQuery += ', '+ field;
            }
            sQuery += ' from ' + objectAPIName + ' where Id=:itemId';
            System.debug('sQuery   '+sQuery);
            sObject obj = Database.query(sQuery);
            for(String field : listFields) {
                for(String sMsg : listMsg) {
                    indexOfMsg = listMsg.indexOf(sMsg);
                	sMsg = sMsg.replaceAll('\\{!'+field+'}', String.valueOf(obj.get(field)));
                    listMsg.set(indexOfMsg, sMsg);
                }
            }
        }
        //System.debug('sMsg   '+sMsg);
        return listMsg;
    }
    
}